version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for npm and yarn
  - package-ecosystem: npm
    directory: "/"
    target-branch: main
    schedule:
      interval: "weekly"
    # Wait at least 10 days after a new version is released before opening a PR
    cooldown:
      default-days: 10
    labels:
      - "dependencies"
      - "npm"
